### PR TITLE
Add information about discontinuation of the project

### PR DESCRIPTION
**Pull request by szadam**
Preview: https://github.com/szadam/miniasync/blob/master/README.md

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmem/miniasync/116)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/116)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @szadam and @wlemkows)

___
*[`README.md` line 92 at r1](https://reviewable.io/reviews/pmem/miniasync/116#-NOFWxcy6GQLc9qe7S99:-NOFWxcy6GQLc9qe7S9A:bnhj6kd) ([raw file](https://github.com/pmem/miniasync/blob/5ce5aefcffe7980b3aedc51ff62751c56ec4892a/README.md#L92)):*
> ```Markdown
> ## Contact Us
> 
> For more information on this library please contact us using dedicated email: pmdk_support@intel.com.
> ```

pls use a similar text to one in pmemstream's PR

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/116)* status: all files reviewed, 1 unresolved discussion (waiting on @szadam and @wlemkows)

**Review by szadam — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/116)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk and @wlemkows)

___
*[`README.md` line 92 at r1](https://reviewable.io/reviews/pmem/miniasync/116#-NOFWxcy6GQLc9qe7S99:-NOy3k5H7Z-VzjcUtH-F:bvwm115) ([raw file](https://github.com/pmem/miniasync/blob/5ce5aefcffe7980b3aedc51ff62751c56ec4892a/README.md#L92)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls use a similar text to one in pmemstream's PR
</blockquote></details>

I propose sth like that

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/116)* status: all files reviewed, 1 unresolved discussion (waiting on @szadam and @wlemkows)

___
*[`README.md` line 92 at r1](https://reviewable.io/reviews/pmem/miniasync/116#-NOFWxcy6GQLc9qe7S99:-NPIpkqpCN6qvxv9Nqqa:b-dw4bbu) ([raw file](https://github.com/pmem/miniasync/blob/5ce5aefcffe7980b3aedc51ff62751c56ec4892a/README.md#L92)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

I propose sth like that
</blockquote></details>

maybe I wasn't too specific with my issue above... Right now the content of this section does not fully make sense - we don't read much `about  miniasync` in the linked blog post. I would re-write this whole section to something like that:

```
## Contact Us

If you read the [blog post](...) and still have some questions (especially about discontinuation of the project), please contact us using the dedicated e-mail: pmdk_support@intel.com.
```

**Review by szadam — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/116)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk and @wlemkows)

___
*[`README.md` line 92 at r1](https://reviewable.io/reviews/pmem/miniasync/116#-NOFWxcy6GQLc9qe7S99:-NPXoT7C6Sstq2zjcQlb:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/5ce5aefcffe7980b3aedc51ff62751c56ec4892a/README.md#L92)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe I wasn't too specific with my issue above... Right now the content of this section does not fully make sense - we don't read much `about  miniasync` in the linked blog post. I would re-write this whole section to something like that:

```
## Contact Us

If you read the [blog post](...) and still have some questions (especially about discontinuation of the project), please contact us using the dedicated e-mail: pmdk_support@intel.com.
```
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/116#-:-NPXv3ES4Ft0N7yu7KGG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wlemkows)

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/116)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wlemkows)

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/116)* status: all files reviewed, 1 unresolved discussion (waiting on @szadam and @wlemkows)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/pmem/miniasync/116#-NQUwOVk5udnl4rC6PYo):*
heh, missing prefix for commit msg - pls start with `doc: add information...`

**Review by szadam — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/116)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk and @wlemkows)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/pmem/miniasync/116#-NQUwOVk5udnl4rC6PYo):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

heh, missing prefix for commit msg - pls start with `doc: add information...`
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/116)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wlemkows)

**Pull request merged**
